name: ci practice

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: running the npm install 
        run: npm install
      - name: running the build
        run: npm run build 
      - name: running the npm test
        run: npm run test 
